### PR TITLE
Push changes in terra/qis_adv for entanglement

### PR DESCRIPTION
**Pull request by aakif-akhtar**
### Details and comments
In the paper https://arxiv.org/pdf/1905.10876.pdf three metrics were proposed to represent Ansatz quality of variational circuits were proposed: Expressibility, Entangling capacity and circuit cost. However, to the best of our knowledge these metrics are not available in Qiskit nor in any of these issues in progress.

We have implemented these metrics and matched our numbers to that of this paper. We have two ways to compute Entangling capacity -using Meyer Wallach measure and Von-Neumann measure.

Changes required in the qiskit.utils library:
Introduced a new folder Entanglement with 3 python scripts with function as follows: (i) parametric_circuit.py - has the circuits comprising of 19 parametric circuits in the https://doi.org/10.1007/s42484-021-00038-w
(ii) meyer_wallach- computes the meyer wallach entanglement measure
(iii) von_neumann - computes the von neumann entanglement measure

### CODE REVIEW

**Comment by Cryoris** [comment]
Nice demo! What do you think about reproducing the entangling capacity plot from Sim et al's paper? Or maybe at least for a single circuit to show that the code matches the expectations? 🙂

**Comment by anupamaray** [comment]
sorry for the late response @Cryoris 
yes we had reproduced all of them, will include it and commit back

**Comment by anupamaray** [comment]
@Cryoris sorry for being so late. I have added the last 4 cells that help compute the entangling capacity for all 19 ansatzes given in Sim etal's paper and show how we can create plots for multiple layers as given in the paper. Now its a complete tutorial for entangling capacity calculation of ansatz and can be extended easily for any type of ansatz. 
Please let me know if u need anything else to merge this pull request.
Thanks

**Review by Cryoris — APPROVED** [review]
LGTM, thanks for the updates! I don't have merging powers but maybe @woodsp-ibm or @1ucian0 could have a look? 🙂

**Comment by woodsp-ibm** [comment]
I think it would be appropriate, since this is a new submission, to have it run against the latest version of Terra, especially given this appears in the output

>/opt/anaconda3/envs/qiskit/lib/python3.6/site-packages/qiskit/__init__.py:66: DeprecationWarning: Using Qiskit with Python 3.6 is deprecated as of qiskit-terra 0.17.0. Support for running Qiskit with Python 3.6 will be removed in qiskit-terra 0.20.0.
  DeprecationWarning,
  
In the latest the import

> from qiskit import Aer

is now deprecated, as the integration into the qikist namespace is being removed. You can see the info here needed to change the import https://qiskit.org/documentation/release_notes.html#qiskit-0-39-0

**Comment by anupamaray** [comment]
thanks Steve, done.
please check and let me know if can be merged now @woodsp-ibm

**Comment by woodsp-ibm** [comment]
Cell 6 appears to have failed with an error message there - and looking at Cell 7 it needs to be adjusted for the Aer import too and re-run.

**Comment by anupamaray** [comment]
@woodsp-ibm thanks for pointing that out. yes that cell was an old code that worked on aersimulator, however as suggested by @Cryoris we modified the following cells to use Statevector class of quantum info instead of aer simulator.  Now the entire code works fine. please check at your end, pushed the updated version of EntanglingCapability.ipynb. Thanks

**Comment by woodsp-ibm** [comment]
If this no longer needs Aer can you remove the import in the first cell so if someone wants to run the notebook its no longer dependent on having Aer installed. 

Also some cells have commented out code for backend.run etc which is, I guess how you were doing things. Can you clean up the cells and remove this old commented out code so people reading it just have the necessary code and do not have to wonder about code that is there which is commented out.

**Comment by anupamaray** [comment]
@woodsp-ibm thanks Steve. cleaned the code and removed all unused lines. Thanks

**Comment by woodsp-ibm** [comment]
@anupamaray Thanks for making the changes. LGTM now.

**Pull request merged**
