### PR TITLE
Update h2_var_forms.ipynb

### PR DESCRIPTION
**Pull request by cpossel**
### Summary

Update h2_var_forms.ipynb to qiskit 0.37.1

### Details and comments

- Update code to be compatible to qiskit 0.37.1
- Replace deprecated qiskit aqua code
- Switch optimizer from COBYLA to faster converging SLSQP
- Add support for any chemistry driver (instead of only PySCF)
- Rerun code with more variational form depths (1 to 10)
- Add side note about interpretation of results with regard to noisy backends

### CODE REVIEW

**Comment by cpossel** [comment]
@woodsp-ibm Is there anything missing to be done from my side for this pull request?

**Review by woodsp-ibm — APPROVED** [review]

**Comment by cpossel** [comment]
@woodsp-ibm Thanks for approving and the information.
Where is the new spot / how is the new way to do things now? Is there a substitute/successor for this repo?

**Comment by woodsp-ibm** [comment]
For the applications (Nature etc) we have tutorials as part of the docs in the repos themselves. For algorithms that are now in Terra, the tutorials are in a qiskit_tutorials repo - which used to have applications one too. So for the main documentation that is part of maintained code thats where it is. We are also looking to change things up with what the tutorials are to also have howtos, examples and reference material.

Anyway as to community tutorials maybe @1ucian0 might know more in regards of this discussion.

**Comment by woodsp-ibm** [comment]
Tutorials that are published as part of the docs for the maintained Qiskit package are managed elsewhere now. As far as additional material such a different tutorials etc from the community I would defer any answer to someone who knows. While we put additional materials here in the past, that were not part of the set that was wanted in the main docs, the goal is to have the docs be comprehensive enough. As to what is happening in regards of this repository again I would have to defer to someone in the community team.

**Pull request merged**
